### ISSUE TITLE
After upgrading to RN 0.60.4 - can't compile. 

### ISSUE THREAD

**Issue by wmonecke** [crazycodeboy/react-native-splash-screen#407]
After having updated to RN 0.60.4 I can't compile on iOS.

Error:
`#import <React/RCTBridgeModule.h> file not found.`

It appears as if `react-native-splash-screen` can't find the React dependency. How do I tell `react-native-splash-screen` where React is? Since 0.60 React is added via `Pods` explicitly.

**Comment by rajeshde** [comment]
I am facing this issue after upgrading to RN 0.60.4

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_RNSplashScreen", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Do I need to add anything specifically in Podfile?
Autolinking worked completely fine in Android

**Comment by jpudysz** [comment]
I was able to compile it with RN 0.60.4

Steps to make it work:
```
react-native unlink react-native-splash-screen
rm -rf Pods
remove pod react-native-splash-screen from Pods if you have one
revert all steps from installation guide for ios: https://github.com/crazycodeboy/react-native-splash-screen
add pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen' to Pods
pod install 
Clean Build in XCode
```

Everything should work now. 

Regarding issue with `OBJC_CLASS$_RNSplashScreen` you need to remove react native splash screen fom Header Search Paths (revert all steps from installation guide)

**Comment by mattop1709** [comment]
Seeking your assistance to upgrade android file inside APP_NAME/node_modules/react-native-splash-screen/android bcoz it happens to Android too (especially when Build Release)..

it still has compile 'com.android.support:appcompat-v7:26.1.0' in the dependencies

**Comment by vinurs** [comment]
since 0.60+, u can use another library https://github.com/zoontek/react-native-bootsplash

**Comment by mattop1709** [comment]
okay then, thanks!

**Comment by M1seRy** [comment]
Same issue `app keeping stopping` . can't compile with RN  ^0.60.0 /  react-native-splash-screen ^3.2.0 in Android。

**Comment by rajeshde** [comment]
> Same issue `app keeping stopping` . can't compile with RN ^0.60.0 / react-native-splash-screen ^3.2.0 in Android。

I just installed it. Auto linking worked completely fine on android. No extra configuration.

For iOS, I followed the installation instruction from README

**Comment by M1seRy** [comment]
@rajeshde  It works now in Android.

I using react-native ^0.60.0 and react-native-splash-screen ^3.2.0, I face the same problem. I solve this issue with:

1. change the code SplashScreen.show(this) with SplashScreen.show(this, true) in android/app/src/main/java/com/yourapp/MainActivity.java :
@Override protected void onCreate(Bundle savedInstanceState) { SplashScreen.show(this, true); // change here super.onCreate(savedInstanceState); }

2. add a launch_screen.xml in your android/app/src/main/res/layout folder with code :
<?xml version="1.0" encoding="utf-8"?> <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android" android:layout_width="match_parent" android:layout_height="match_parent" android:background="@drawable/launch_screen" android:orientation="vertical"> </LinearLayout>

3. add colors.xml in your android/app/src/main/res/values folder with code:
<?xml version="1.0" encoding="utf-8"?> <resources> <color name="primary_dark">#000000</color> </resources>

The README or guide document should be updated.

Good luck.

**Comment by erkangozukucuk** [comment]
> I was able to compile it with RN 0.60.4
> 
> Steps to make it work:
> 
> ```
> react-native unlink react-native-splash-screen
> rm -rf Pods
> remove pod react-native-splash-screen from Pods if you have one
> revert all steps from installation guide for ios: https://github.com/crazycodeboy/react-native-splash-screen
> add pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen' to Pods
> pod install 
> Clean Build in XCode
> ```
> 
> Everything should work now.
> 
> Regarding issue with `OBJC_CLASS$_RNSplashScreen` you need to remove react native splash screen fom Header Search Paths (revert all steps from installation guide)

yes i can build app but splash screen not wait until finish async background action. It seem a second then disappear.

**Comment by solfKwolf** [comment]
> @rajeshde It works now in Android.
> 
> I using react-native ^0.60.0 and react-native-splash-screen ^3.2.0, I face the same problem. I solve this issue with:
> 
> 1. change the code SplashScreen.show(this) with SplashScreen.show(this, true) in android/app/src/main/java/com/yourapp/MainActivity.java :
> 
> `@Override protected void onCreate(Bundle savedInstanceState) { SplashScreen.show(this, true); // change here super.onCreate(savedInstanceState); }`
> 
> 1. add a launch_screen.xml in your android/app/src/main/res/layout folder with code :
> 
> `<?xml version="1.0" encoding="utf-8"?> <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android" android:layout_width="match_parent" android:layout_height="match_parent" android:background="@drawable/launch_screen" android:orientation="vertical"> </LinearLayout>`
> 
> 1. add colors.xml in your android/app/src/main/res/values folder with code:
>    `<?xml version="1.0" encoding="utf-8"?> <resources> <color name="primary_dark">#000000</color> </resources>`
> 
> The README or guide document should be updated.
> 
> Good luck.

I using react-native ^0.60.4 and react-native-splash-screen ^3.2.0，i try your solution , but  it no use

**Comment by smxdevst** [comment]
Same issue and Android is keep crushing on launch

**Comment by jedashford** [comment]
I needed to make this change, now android loads fine on .60
```import com.facebook.soloader.SoLoader;```
```@Override
    protected void onCreate(Bundle savedInstanceState) {
        SoLoader.init(this, false);
        SplashScreen.show(this, R.style.SplashTheme);  // here
        super.onCreate(savedInstanceState);

    }```

**Comment by sasclau** [comment]
Android is keep crushing on real device only
